development:
  adapter: postgresql
  encoding: unicode
  database: discourse_11
  pool: 5
  username: bittern105
  password: root
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: discourse_12
  pool: 5
  username: bittern105
  password: root
  host: localhost
